### ISSUE TITLE
UDP port netflow/IPfix

### ISSUE THREAD

**Issue by swish1** [javadmohebbi/goNfCollector#8]
Hello. I want to thank you for the wonderful installation script. But I ran into a problem. For some reason UDP port 6859 is occupied only by ipv6. And for ipv4, it does not take. Accordingly, the ipfix collector does not work. Please help me. How to fully run the collector?
 To start containers:
 $ cd /root/oi24/nfcollector && docker-compose up -d

netflow enabled:
root@netflow:~/oi24/nfcollector# tcpdump port 6859
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:24:31.993683 IP IP_router.4739 > IP_goEfCOllector.6859: UDP, length 89
17:24:32.993683 IP IP_router.4739 > IP_goEfCOllector.6859: UDP, length 89
17:24:33.993683 IP IP_router.4739 > IP_goEfCOllector.6859: UDP, length 89

not lisen port 6859 udp ipv4 , only ipv6
root@netflow:~/oi24/nfcollector# netstat -anu
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 127.0.0.1:123           0.0.0.0:*
udp        0      0 0.0.0.0:123             0.0.0.0:*
udp6       0      0 :::6859                 :::*

Thanks

**Comment by javadmohebbi** [comment]
Hi @swish1 

On Linux systems net.ipv6.bindv6only is 0, so ipv4 packets also can be  received from ipv6 sockets with ipv4-mapped ipv6 address. So, currently there is no problem at all with your `netstat` command output.

What is the device you are exporting `IPFIX` from? And please also do the further steps to let me know more about your `IPFIX` template.

please run the following commad for gathering some logs for further investigations. This command will run a special version of nfcollector which logs decoded netflow packets to a log file `/tmp/nfcollector-dump.log`

```
# Stopping the running containers
/root/oi24/nfcollector && docker-compose down


cd $HOME/oi24/nfcollector
docker-compose down
wget -O /tmp/nfcollector-logger https://github.com/javadmohebbi/goNfCollector/raw/main/build/linux/amd64/nfcollector-logger
chmod +x /tmp/nfcollector-logger
sudo /tmp/nfcollector-logger 
```
To stop this app, press CTRL + C
After that, log file will be /tmp/nfcollector-dump.log.
*** This file might include some confidential info about IPs. Due to security reason, you can find & replace your confidential information***

Please send me back the `/tmp/nfcollector-dump.log` file.

Regards

**Comment by swish1** [comment]
Thanks @javadmohebbi 
# cat /tmp/nfcollector-dump.log
IPFIX message
IPFIX message
IPFIX message
IPFIX message
IPFIX message
IPFIX message
IPFIX message
IPFIX message


I am using software  DPDK router. According to the instructions on the website: 
https://github.com/alexk99/the_router/ 
and enable IPFIX:
https://github.com/alexk99/the_router/blob/master/conf_options2.md#flow-accounting-ipfix

**Comment by javadmohebbi** [comment]
Hi @swish1 

Thank you for the provided information. You are exporting Flow Accounting to the **netflow collector**. Also **Netflow Collector** can decode IPFIX **RFC5102** template not all the custom templates.

```
        (DECODED)   sourceIPv4Address: IP
        (DECODED)   destinationIPv4Address: IP
        (DECODED)   protocolIdentifier: 6
        packetTotalCount: 7
        octetTotalCount: 1508
        ipv4Options: 0
        flowEndReason: 3
        flowStartMilliseconds: 2021-06-08 15:15:35 +0300 MSK
        flowEndMilliseconds: 2021-06-08 15:15:35 +0300 MSK
        ingressPhysicalInterface: 3
        egressPhysicalInterface: 2
        ipClassOfService: 0
        (DECODED)   sourceTransportPort: 61976
        (DECODED)   destinationTransportPort: 443
        tcpOptions: 0
        (DECODED) tcpControlBits: 29
```
In above flow record set **netflow collector app** can decode the ones I mentioned above according to **RFC5102**.

Please read your router dos and try to export Netflow V9 and let me know the result.

**Comment by swish1** [comment]
@javadmohebbi 

I hid the IP address. This is how the real IP address is displayed. It’s a pity that this doesn’t suit me. Thank you

**Comment by javadmohebbi** [comment]
> @javadmohebbi 
> 
> I hid the IP address. This is how the real IP address is displayed. It’s a pity that this doesn’t suit me. Thank you


I think I could do some small changes to help you use this app. But it takes time. I will let you know when its ready

**Comment by javadmohebbi** [comment]
> @javadmohebbi 
> 
> I hid the IP address. This is how the real IP address is displayed. It’s a pity that this doesn’t suit me. Thank you

And have you tried netflow v9?

**Comment by swish1** [comment]
@javadmohebbi 
Unfortunately, Netflow v9 support is not supported by this DPDK router. Thank you for helping

**Comment by alexk99** [comment]
Hi @javadmohebbi 

> In above flow record set **netflow collector app** can decode the ones I mentioned above according to **RFC5102**.

Could please explain why your software can not decode the rest of the fields? let's take a look for example at the packetTotalCount field. It's described here https://datatracker.ietf.org/doc/html/rfc5102#section-5.10.10

**Comment by swish1** [comment]
@javadmohebbi Hello. Any update?
I check netflow v9 . Not work

**Comment by javadmohebbi** [comment]
Dear @alexk99 and @swish1 

Currently I am working on a feature to let users customize their Fields in the netflow records. Since currently there are many users who has problem with IPFIX and V9. 

I hope this feature will be ready within 2 weeks. Hope it will fix your problem.

**Comment by javadmohebbi** [comment]
> Hi @javadmohebbi
> 
> > In above flow record set **netflow collector app** can decode the ones I mentioned above according to **RFC5102**.
> 
> Could please explain why your software can not decode the rest of the fields? let's take a look for example at the packetTotalCount field. It's described here https://datatracker.ietf.org/doc/html/rfc5102#section-5.10.10

Thank you for the provided information. It's now a known issue and I will let you know when it's fixed. Thank you.

**Comment by javadmohebbi** [comment]
> Hello. Are there any updates? I have checked for v9 and ipfix. Also does not work ((

Hi @swish1

Have you tried the latest vesrion?

Please provide the output of the further command

```
docker exec oi24_nfcollector_1 nfcollector -version
```

**Comment by javadmohebbi** [comment]
Hi @swish1, 

Does your problem fixed or the issue still persists? If it does not, please let me know and for the remote session, send an email to [javad [at] openintelligence24 [dot] com](javad@openintelligence24.com)

**Comment by swish1** [comment]
> Hi @swish1,
> 
> Does your problem fixed or the issue still persists? If it does not, please let me know and for the remote session, send an email to [javad [at] openintelligence24 [dot] com](javad@openintelligence24.com)

Hello. I sent a test access to the mail. Problem not fixed

**Comment by javadmohebbi** [comment]
> > Hi @swish1,
> > Does your problem fixed or the issue still persists? If it does not, please let me know and for the remote session, send an email to [javad [at] openintelligence24 [dot] com](javad@openintelligence24.com)
> 
> Hello. I sent a test access to the mail. Problem not fixed

Hi @swish1 

I have connected to your server using SSH and fixed your problem and our own `docker-compose.yml` file. Our dashboard should be run on `grafana:7.5.0` docker image and I have fixed that for you. Again thank you for your time. Now open your grafana dashboard and enjoy ;-). Also, I replied your Email ;-)

**Comment by hiendinh114** [comment]
Hi @javadmohebbi . I find your application very useful. I have used it successfully with devices that support Netflow v5 and Netflow v9. However, I am having a problem with openvswitch when I have to monitor both IPv4 and IPv6 simultaneously. openvswitch (v3.0.3) does not support Netflow v9. I tried using ipfix but got problem when edit the etc/trans.yml file.

**Comment by hiendinh114** [comment]
Hi @javadmohebbi . I find your application very useful. I have used it successfully with devices that support Netflow v5 and Netflow v9. However, I am having a problem with openvswitch when I have to monitor both IPv4 and IPv6 simultaneously. Openvswitch (v3.0.3) does not support Netflow v9. I tried using IPFIX instead but got problem when edit the etc/trans.yml file.

OVS's IPFIX message doesn't have the fields: ipNextHopIPv4Address, tcpControlBits, destinationIPv4PrefixLength, sourceIPv4PrefixLength.

OVS's IPFIX message also have both octetDeltaCount and octetTotalCount for the octetDeltaCount mapping.

I tried both deleting the missing fields in etc/trans.yml file and mapping them to random fields in OVS's IPFIX message but didn't work.

Please tell me what I can do next. 

-----------
Here is the OVS's IPFIX message in my case. Thank you very much.

```
IPFIX message
    data set
        1 records:
            record 0:
                observationPointId: 456
                flowDirection: 1
                sourceMacAddress: f8:66:f2:69:0b:ff
                destinationMacAddress: fa:16:3e:6f:b2:56
                ethernetType: 2048
                ethernetHeaderLength: 14
                ingressInterface: 0
                ingressInterfaceType: 0
                interfaceName:
                interfaceDescription:
                egressInterface: 12582241
                egressInterfaceType: 0
                interfaceName: vhu0a616e3a-a1
                interfaceDescription:
                ipVersion: 4
                ipTTL: 63
                protocolIdentifier: 17
                ipDiffServCodePoint: 0
                ipPrecedence: 0
                ipClassOfService: 0
                sourceIPv4Address: 192.168.53.32
                destinationIPv4Address: 192.168.55.130
                sourceTransportPort: 49049
                destinationTransportPort: 6859
                flowStartDeltaMicroseconds: 33000
                flowEndDeltaMicroseconds: 33000
                droppedPacketDeltaCount: 400
                droppedPacketTotalCount: 1200
                packetDeltaCount: 400
                packetTotalCount: 1200
                ingressUnicastPacketTotalCount: 0
                ingressMulticastPacketTotalCount: 0
                ingressBroadcastPacketTotalCount: 0
                egressUnicastPacketTotalCount: 1200
                egressBroadcastPacketTotalCount: 0
                postMCastPacketDeltaCount: 0
                postMCastPacketTotalCount: 0
                layer2OctetDeltaCount: 504800
                layer2OctetTotalCount: 1709600
                flowEndReason: 5
                drop pedOctetDeltaCount: 499200
                droppedOctetTotalCount: 1692800
                octetDeltaCount: 499200
                octetTotalCount: 1692800
                octetDeltaSumOfSquares: 623001600
                octetTotalSumOfSquares: 2403852800
                minimumIpTotalLength: 1248
                maximumIpTotalLength: 1248
                postMCastOctetDeltaCount: 0
                postMCastOctetTotalCount: 0
```
